[workspace]
members = [ 
	"main",
	"logical",
	"base_language",
	"integer",
	"double",
	"character",
	"complex",
	"value",
	"list",
	"base_parser",
	"union",
	"vector",
	"expression",
	"command",
	"checker",
	"transpiler",
]
