[package]
name = "transpiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
command = { path = "../command" }
checker = { path = "../checker" }
base_language = { path = "../base_language" }
